### ISSUE TITLE
v2.3.3 - NullPointerException in PasswordActivity.checkFilePermissions(PasswordActivity.java:571)

### ISSUE THREAD

**Issue by DavidMaza** [bpellin/keepassdroid#299]
After upgrading to v2.3.3, I get the below exception when trying to open a database:

```
06-25 09:46:00.757 25895-25895/? E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.android.keepass, PID: 25895
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
at com.keepassdroid.PasswordActivity.checkFilePermissions(PasswordActivity.java:571)
at com.keepassdroid.PasswordActivity.loadDatabase(PasswordActivity.java:617)
at com.keepassdroid.PasswordActivity.loadDatabase(PasswordActivity.java:566)
at com.keepassdroid.PasswordActivity.access$900(PasswordActivity.java:83)
at com.keepassdroid.PasswordActivity$OkClickHandler.onClick(PasswordActivity.java:558)
at android.view.View.performClick(Unknown Source:15)
at android.view.View$PerformClick.run(Unknown Source:2)
at android.os.Handler.handleCallback(Unknown Source:2)
at android.os.Handler.dispatchMessage(Unknown Source:4)
at android.os.Looper.loop(Unknown Sourc

```

**Comment by ascendedguard** [comment]
I'm also crashing when trying to open a database starting today, I'm guessing it's the same error but haven't tried to view the logs.
