### ISSUE TITLE
[CRASH] IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity

### ISSUE THREAD

**Issue by ildar** [bpellin/keepassdroid#386]
Android 7.1 (CM-14.1)
After app upgrade (from F-Droid) I tap on `OPEN DATABASE` button and app crashes.

```
02-26 14:14:58.626 11353 11353 E AndroidRuntime: FATAL EXCEPTION: main
02-26 14:14:58.626 11353 11353 E AndroidRuntime: Process: com.android.keepass, PID: 11353
02-26 14:14:58.626 11353 11353 E AndroidRuntime: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.app.Dialog.dispatchOnCreate(Dialog.java:402)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.app.Dialog.show(Dialog.java:301)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:486)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:183)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.biometric.BiometricPrompt.authenticateInternal(BiometricPrompt.java:797)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at androidx.biometric.BiometricPrompt.authenticate(BiometricPrompt.java:649)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at com.keepassdroid.fragments.PasswordFragment$1.onClick(PasswordFragment.java:158)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
02-26 14:14:58.626 11353 11353 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
02-26 14:14:58.632  4554 10616 W ActivityManager:   Force finishing activity com.android.keepass/com.keepassdroid.PasswordActivity
```

**Comment by bpellin** [comment]
This is fixed in version 2.5.3.
