### ISSUE TITLE
KeePassDroid 2.6.2 (beta) crashes at startup

### ISSUE THREAD

**Issue by rrayst** [bpellin/keepassdroid#485]
KeePassDroid 2.6.2 (beta) crashes at startup. The exception is:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.keepass/com.keepassdroid.fileselect.FileSelectActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at com.keepassdroid.utils.UriUtil.getFileName(UriUtil.java:168)
	at com.keepassdroid.fileselect.RecentFileHistory.getDbList(RecentFileHistory.java:234)
	at com.keepassdroid.fileselect.FileSelectActivity.fillData(FileSelectActivity.java:405)
	at com.keepassdroid.fileselect.FileSelectActivity.onCreate(FileSelectActivity.java:312)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8269)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
	... 12 more
```

**Comment by rrayst** [comment]
Fixed in ddff2e8e87d3ec8cdf4ab48b293dd3373cb99b72 .
